Resources:
  SalesforceSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: salesforce-key
      Description: This secret has a hardcoded password and security token in SecretString
      SecretString: '{"username":"","password":"","security_token":""}'
      Tags:
        -
          Key: Environment
          Value: Dev

Outputs:
  SalesforceSecretArn:
    Value: !Ref SalesforceSecret
    Export:
      Name: SalesforceSecretArn