Resources:
  DailyCostBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      Tags:
        - Key: Name
          Value: DailyCostBucket

  DailyCostBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'DailyCostBucket'
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: billingreports.amazonaws.com
            Action:
              - s3:GetBucketAcl
              - s3:GetBucketPolicy
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref 'DailyCostBucket'
          - Effect: Allow
            Principal:
              Service: billingreports.amazonaws.com
            Action: s3:PutObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref 'DailyCostBucket'
                - /*

  DailyCostReport:
    Type: AWS::CUR::ReportDefinition
    Properties:
      ReportName: DailyCostReport
      TimeUnit: DAILY
      Format: textORcsv
      S3Bucket: !Ref DailyCostBucket
      S3Prefix: cur/
      S3Region: us-east-1
      Compression: GZIP
      RefreshClosedReports: false
      ReportVersioning: OVERWRITE_REPORT